### ISSUE TITLE
[Feature Request] Fallback proxy group

### ISSUE THREAD

**Issue by soffchen** [SagerNet/sing-box#102]
Fallback proxy group in clash is useful for choosing preferred proxies in group. e.g. place HK proxies becore JP proxies, when HK  proxy dies, choose JP proxy automatically.
```
  # fallback selects an available policy by priority. The availability is tested by accessing an URL, just like an auto url-test group.
  - name: "fallback-auto"
    type: fallback
    proxies:
      - hk1
      - hk2
      - hk1
      - hk2
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
```

Source code: [https://github.com/Dreamacro/clash/blob/master/adapter/outboundgroup/fallback.go](https://github.com/Dreamacro/clash/blob/master/adapter/outboundgroup/fallback.go)
