### ISSUE TITLE
Docker tun 入站无法使用 ipv6

### ISSUE THREAD

**Issue by cutiechi** [SagerNet/sing-box#1966]
### Operating system

Linux

### System version

ubuntu 2204

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.9.3

Environment: go1.22.4 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 085f60337799afc906069b540a38368968c123e4
CGO: disabled
```

### Description

tun 入站一旦配置了 inet6_address docker 容器就无法启动，不配置的时候无任何问题

### Reproduction

docker compose yaml:

```yaml
name: sing-box
services:
  clash-meta:
    cap_add:
      - DAC_READ_SEARCH
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_PTRACE
    command:
      - -D
      - /root/.config/sing-box
      - -C
      - /root/.config/sing-box/
      - run
    container_name: sing-box
    devices:
      - /dev/net/tun
    image: ghcr.io/sagernet/sing-box:latest
    networks:
      macvlan:
        ipv4_address: 192.168.50.14
    restart: always
    volumes:
      - type: bind
        source: /home/cutiechi/configurations/sing-box/config.json
        target: /root/.config/sing-box/config.json
        bind:
          create_host_path: true
      - type: bind
        source: /home/cutiechi/datas/sing-box
        target: /root/.config/sing-box
        bind:
          create_host_path: true
networks:
  macvlan:
    name: macvlan
    external: true
```

tun 入站:
```json
    {
      "type": "tun",
      "tag": "tun",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fd00::1/126",
      "auto_route": true,
      "sniff": true,
      "sniff_override_destination": true
    },
```

### Logs

```shell
报错日志： 
start service: initialize inbound/tun[0]: configure tun interface: permission denied
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.
