### ISSUE TITLE
Hysteria2性能优化(QUIC 流控制接收窗口参数)

### ISSUE THREAD

**Issue by YUxiangLuo** [SagerNet/sing-box#2133]
用sing-box和hysteria2各自的客户端进行测试，"down_mbps"都设置为900，两者没有区别，测速都只能跑到450左右的速度。

然后给hysteria2的配置文件添加quic配置
```yaml
quic:
  initStreamReceiveWindow: 53687090
  maxStreamReceiveWindow: 53687090
  initConnReceiveWindow: 134217728
  maxConnReceiveWindow: 134217728
```
此时hysteria2官方客户端可以跑到900左右的速度。
sing-box是否也有类似的配置？找了一下没有找到。
