### ISSUE TITLE
The TUN mode of sing-box causes Docker Bridge mode to fail.

### ISSUE THREAD

**Issue by sky22333** [SagerNet/sing-box#2700]
The TUN mode of sing-box causes Docker's Bridge mode to fail. Specifically, it prevents public access. When using `curl 127.0.0.1:8080` on the host machine, access works fine, but if Docker is set to Bridge mode, it does not work. However, everything functions normally when using Docker's Host mode. The proxy is also successful.

Here is my sing-box configuration. Could you help me identify the issue? Thanks!

The sing-box version is `v1.11.4`.

```
{
  "log": {
    "level": "info"
  },
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "tls://8.8.8.8"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "sing-tun",
      "mtu": 9000,
      "sniff": true,
      "address": [
        "10.254.0.1/24",
        "fd00::1/64"
      ],
      "auto_route": true,
      "strict_route": true
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy",
      "server": "123.123.123.123",
      "server_port": 8443,
      "uuid": "xxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxxx",
      "tls": {
        "enabled": true,
        "server_name": "tesla.com",
        "insecure": false,
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "short_id": "xxxxxxxxxx"
        }
      },
      "transport": {
        "type": "grpc",
        "service_name": ""
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "protocol": "dns",
        "outbound": "direct"
      },
      {
        "ip_version": 6,
        "outbound": "proxy"
      },
      {
        "inbound": ["tun-in"],
        "network": "tcp",
        "port": [22],
        "outbound": "direct"
      },
      {
        "geoip": ["private"],
        "outbound": "proxy"
      },
      {
        "ip_cidr": [
          "192.168.0.0/16",
          "127.0.0.1/32",
          "fc00::/7"
        ],
        "outbound": "direct"
      }
    ],
    "final": "proxy"
  }
}
```

**Comment by HenryHe613** [comment]
I'm experiencing the same issue. `127.0.0.1:1081` is accessible, and TUN is functioning correctly on the host. However, none of my bridge mode Docker containers can access the external network. The sing-box logs show correct DNS resolution within the containers, but there's no indication of TUN connectivity.

I suspect the issue lies with iptables not modifying the Docker network settings, or potentially incorrect IP routing.

(Minor suggestion: The official documentation could benefit from timely updates.)

```json
{
  "log": {
    "level": "debug"
  },
  "dns": {
    "servers": [
      {
        "tag": "ali",
        "address": "223.5.5.5",
        "detour": "direct"
      },
      {
        "address": "local",
        "tag": "hosts"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "mixed",
      "tag": "mixed",
      "listen": "127.0.0.1",
      "listen_port": 1081
    },
    {
      "type": "tun",
      "tag": "tun",
      "interface_name": "tun0",
      "address": "192.168.100.1/24",
      "auto_route": true,
      "auto_redirect": true,
      "strict_route": true,
      "stack": "system",
      "mtu": 1492
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "server": "xxx",
      "server_port": 80,
      "uuid": "xxx",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": {
        "enabled": true,
        "server_name": "xxx"
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "dns",
      "tag": "dns"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "port": 53,
        "outbound": "dns"
      }
    ]
  }
}
```

**Comment by HenryHe613** [comment]
> [@HenryHe613](https://github.com/HenryHe613) Have you solved this problem?

Not yet. I find this [closed issue](https://github.com/SagerNet/sing-box/issues/1685). Is it a 'feature'?

**Comment by HenryHe613** [comment]
You may need to change some configurations for yourself. Here is the official doc. [https://wiki.metacubex.one/](https://wiki.metacubex.one/)

```yaml
mixed-port: 7890

allow-lan: true
lan-allowed-ips: # FOR DOCKER
  - 172.17.0.0/16
  - 172.18.0.0/15
  - 172.20.0.0/14

mode: rule

log-level: debug

external-controller: '127.0.0.1:9090'

tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  device: utun0
  mtu: 9000
  strict-route: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
  use-hosts: true

hosts:
  doh.pub: [
    '120.53.53.53',
    '1.12.12.21'
  ]
  dns.alidns.com: [
    '223.5.5.5',
    '223.6.6.6'
  ]

proxies:
  - name: "SS"
    type: ss
    server: ss.example.com
    port: 80
    cipher: chacha20-ietf-poly1305
    password: "xxx"

rules:
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,SS
```
