### ISSUE TITLE
Docker怎么配置才能让Hysteria2的ACME的证书持久化呢？

### ISSUE THREAD

**Issue by toyo2333** [SagerNet/sing-box#2970]
```
services:
    
    sbox:
        image: ghcr.io/sagernet/sing-box
        container_name: sbox
        restart: always
        logging:
            options:
                max-size: 10m
        ports:
            - "443:443"
            - "443:443/udp"        
        # network_mode: "host"
        volumes:
            - ./sbox:/etc/sing-box/
        command: -D /var/lib/sing-box -C /etc/sing-box/ run
```

我是这样启动的，配置的HY2，自动获取证书。

但我发现重启了几次容器后，就启动不了了，发现报错
**"HTTP 429 urn:ietf:params:acme:error:rateLimited - too many certificates (5) already issued for this exact set of domains in the last 168h0m0s, ”**

之前使用HY2官方的Docker方式运行的时候，目录是这样映射的：
```
        volumes:
            - ./hysteria/container-data:/acme
            - ./hysteria/container-config/hysteria.yaml:/etc/hysteria.yaml
```

现在我在Sing-box这用Dockers运行的互啊，我应该在volumes:里映射哪个目录可以使得证书可以持久化下来，避免每次启动服务得重新申请然后出现上述报错
