### ISSUE TITLE
anyTLS + Reality 连不上

### ISSUE THREAD

**Issue by toyo2333** [SagerNet/sing-box#3008]
服务端，sing-box最新测试版（docker运行）
客户端，mihomo最新正式版

客户端配置
```
- name: anytls
  type: anytls
  server: <vps-ip-address>
  port: 443
  password: "<password>"
  udp: true
  tls: true
  # sni: some-domain.com
  servername: some-domain.com
  reality-opts:
    public-key: "<public-key>"
    short-id: "<short-id>"
```
这里我sni和servername都分别设置或者同时设置了，都不行

服务端配置
```
{
      "type": "anytls",
      "tag": "anytls-in",
      "listen": "::",
      "listen_port": 443,
      "users": [
        {
          "name": "trump",
          "password": "<password>"
        }
      ],
      "padding_scheme": [
        "stop=8",
        "0=30-30",
        "1=100-400",
        "2=400-500,c,500-1000,c,500-1000,c,500-1000,c,500-1000",
        "3=9-9,500-1000",
        "4=500-1000",
        "5=500-1000",
        "6=500-1000",
        "7=500-1000"
      ],
      "tls": {
        "enabled": true,
        "server_name": "some-domain.com",
        "reality": {
          "enabled": true,
          "handshake": {
            "server": "some-domain.com",
            "server_port": 443
          },
          "private_key": "private_key",
          "short_id": [
            "short_id"
          ]
        }
      }
    }
```

运行后，连接服务端，报错
```
INFO [1171663528 0ms] inbound/anytls[anytls-in]: inbound connection from <my-ip-address>:4852
ERROR [1171663528 446ms] inbound/anytls[anytls-in]: process connection from <my-ip-address>:4852: TLS handshake: REALITY: processed invalid connection
```

域名本身没问题，之前给vless+vision+reality 用了挺久了
