### ISSUE TITLE
docker 更新最新的测试版后启动失败

### ISSUE THREAD

**Issue by toyo2333** [SagerNet/sing-box#3020]
docker compose配置文件如下
```
services:

    sb:
        image: ghcr.io/sagernet/sing-box:latest-beta
        container_name: singbox
        restart: always
        logging:
            options:
                max-size: 10m
        ports:
            - "443:443/udp"
        environment:
            - TZ=Asia/Shanghai
            - XDG_DATA_HOME=/data
        volumes:
            - ./singbox/acme:/data
            - ./singbox:/etc/sing-box/
        command: -D /var/lib/sing-box -C /etc/sing-box/ run
```

singbox服务端只配置了一个hy2.

docker compose pull之后

第一次使用docker compose up -d 发现服务没起来，进去看了下日志只有这一段：
```
| 1.7479804632094386e+09    info    maintenance     stopped background certificate maintenance      {"cache": "0xc000396480"}
| 1.7479804632199824e+09    info    maintenance     stopped background certificate maintenance      {"cache": "0xc000396600"}
```

然后再执行一次 docker compose up -d

发现把我原来那个容器删掉了，然后创建了一个新的启动起来了，但是名字变了。
[+] Running 2/2
 ✔ Container singbox               Removed                                                                                                                                                                0.0s 
 ✔ Container 17236ebbda8f_singbox  Started   

我之前的习惯都是这样来更新容器服务的，其他的容器服务也一直这样更新，没有出现过问题。

sing-box的这个情况 我遇到过两次，第一次是是更新正式版，tag用的是:latest。更新后启动不成功

这是第二次。
