### ISSUE TITLE
服务端docker部署sing-box，tun接口，ipv6无法连接入站

### ISSUE THREAD

**Issue by Atoii** [SagerNet/sing-box#458]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

环境：oracle ubuntu系统
部署方法：docker compose
问题描述：使用docker部署sing-box，网络为host模式，设置了wireguard出站，并使用tun接口接管所有流量，如果设置"inet6_address"，则出站ipv6流量可以正常分流到wireguard，但是入站无法通过ipv6连接。不设置"inet6_address"，则入站可以通过ipv6连接，但出站无法分流ipv6到wireguard。

### Version of sing-box

sing-box version 1.1.7

### Server and client configuration file

配置如下：
```
docker compose配置
version: "3.8"

services:
  web-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    restart: always
    network_mode: host
    command: run -c /etc/sing-box/config.json
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config.json:/etc/sing-box/config.json
      - ./cert.crt:/etc/cert.crt
      - ./cert.key:/etc/cert.key
      - /etc/hosts:/etc/hosts

```
sing-box配置如下
```
{
    "dns": {
        "servers": [
            {
                "tag": "SDNS",
                "address": "local",
                "strategy": "prefer_ipv4",
                "detour": "direct"
            }
        ],
        "final": "SDNS",
        "disable_cache": false,
        "disable_expire": false
    },
    "inbounds": [
        {
            "type": "tun",
            "tag": "tun-in",
            "interface_name": "tun0",
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "fc00::a/126",
            "auto_route": true,
            "strict_route": false,
            "stack": "system",
            "sniff": true
        },
        {
            "type": "vmess",
            "tag": "vmess-in",
            "listen": "::",
            "listen_port": 8080,
            "tcp_fast_open": true,
            "udp_fragment": true,
            "sniff": true,
            "sniff_override_destination": true,
            "udp_timeout": 300,
            "users": [
                {
                    "name": "vmess",
                    "uuid": "ffffffff-ffff-ffff-ffff-fffffffffff",
                    "alterId": 0
                }
            ],
            "transport": {
                "type": "ws",
                "path": "/path"
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        },
        {
            "type": "wireguard",
            "tag": "wireguard-out",
            "server": "162.159.195.1",
            "server_port": 500,
            "system_interface": true,
            "interface_name": "wg0",
            "local_address": [
            	"172.16.0.2/32",
            	"ipv6address/128"
            ],
            "private_key": "私钥=",
            "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "mtu": 1420,
            "bind_interface": "ens3",//oracle_amd64_ubuntu网卡名
            "tcp_fast_open": true,
            "udp_fragment": true
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "geoip": [
                	"cn",
                	"telegram"
                ],
                "geosite": ["cn"],
                "domain_suffix": ["ai.com"],
                "domain_keyword": ["openai"],
                "outbound": "wireguard-out"
            }
        ],
        "geoip": {
            "path": "/etc/geoip.db",
            "download_url": "https://github.com/lyc8503/sing-box-rules/releases/latest/download/geoip.db",
            "download_detour": "direct"
        },
        "geosite": {
            "path": "/etc/geosite.db",
            "download_url": "https://github.com/lyc8503/sing-box-rules/releases/latest/download/geosite.db",
            "download_detour": "direct"
        },
        "final": "direct",
        "default_interface": "ens3"//oracle_amd64_ubuntu网卡名
    }
}
```
### Server and client log file

none
