### ISSUE TITLE
Q: Does sing-box support rule providers, like Clash?

### ISSUE THREAD

**Issue by shvchk** [SagerNet/sing-box#660]
With Clash, I can subscribe to rules published online, and then apply policy to these rules, like this:

```yml
rule-providers:
  blocked:
    type: http
    behavior: domain
    url: 'https://example.com/clash-rules/blocked'
    path: ./ruleset/blocked
    interval: 86400

rules:
  - RULE-SET,blocked,proxy
  - MATCH,DIRECT
```

Does sing-box support something similar?
